pihole_ip: "{{ lookup('ansible.builtin.env', 'TF_VAR_pihole_ip') }}"
truenas_ip: "{{ lookup('ansible.builtin.env', 'TF_VAR_truenas_ip') }}"
api_password: "{{ lookup('ansible.builtin.env', 'TF_VAR_pihole_api_password') }}"

pihole_dns_hosts:
  - hostname: homelab.home.arpa
    address: "{{ truenas_ip }}"

  - hostname: jellyfin.home.arpa
    address: "{{ truenas_ip }}"

  - hostname: pihole.home.arpa
    address: "{{ pihole_ip }}"

  - hostname: truenas.home.arpa
    address: "{{ truenas_ip }}"

pihole_dns_upstreams:
  - 8.8.8.8
  - 8.8.4.4

pihole_adlists:
  - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts