all:
  children:
    homelab:
      hosts:
        pihole:
          ansible_host: "{{ lookup('ansible.builtin.env', 'TF_VAR_pihole_ip') }}"
          ansible_user: "{{ lookup('ansible.builtin.env', 'TF_VAR_bbb_username') }}"
          ansible_password: "{{ lookup('ansible.builtin.env', 'TF_VAR_bbb_password') }}"
          ansible_become_password: "{{ lookup('ansible.builtin.env', 'TF_VAR_bbb_password') }}"
        truenas:
          ansible_host: "{{ lookup('ansible.builtin.env', 'TF_VAR_truenas_ip') }}"

    local:
      hosts:
        workstation:
          ansible_connection: local
