---
- name: Configure workstation
  hosts: workstation
  gather_facts: true

  tasks:
    - name: Display operating system
      ansible.builtin.debug:
        msg: "{{ ansible_facts['distribution'] }} {{ ansible_facts['distribution_version'] }}"

    - name: Display architecture
      ansible.builtin.debug:
        msg: "{{ ansible_facts['architecture'] }}"

    - name: Display hostname
      ansible.builtin.debug:
        msg: "{{ ansible_facts['hostname'] }}"

    - name: Ensure workstation packages are installed
      become: true
      ansible.builtin.apt:
        name: "{{ workstation_packages }}"
        state: present
        update_cache: true
